// Automatisch generiert aus chest_mapping_analysis.csv
export const CHEST_NAMES = [
  "Ancient Warrior's Chest","Ancients' Chest","Arena","Barbarian Chest","Bone Chest","Braided Chest","Cobalt Chest","Cobra Chest","Common Chest of Wealth","Conqueror's Chest","Cursed Chest","Cursed Citadel Chest","Elegant Chest","Elven Chest","Elven Citadel Chest","Epic Chest of Wealth","Fire Chest","Forgotten Chest","Gladiator's Chest","Gnome Workshop Chest","Golden Guardian Epic Chest","Harpy Chest","House of Horrors Chest","Infernal Chest","Jormungandr's Chest","Magic Chest","Mayan Chest","Merchant's Chest","Minotaur Chest","Orc Chest","Pacified Mimic Chest","Precious Chest","Priest's Chest","Quick March Chest","Runic Chest","Rare Chest of Wealth","Rare Dragon Chest","Sand Chest","Sapphire Chest","Scarab Chest","Scorpion Chest","Stone Chest","Tartaros Chest","Titansteel Chest","Trillium Chest","Turtle Chest","Uncommon Chest of Wealth","Undead Chest","Union Chest","White Wood Chest","Wooden Chest"
];

export const CHEST_TYPES = [
  "Arena","Bank","Citadel","Clan wealth","Common Crypt","epic Crypt","Epic Ancient squad","heroic Monster","Mercenary Exchange","Raid Runic squad","rare Crypt","Rise of the Ancients event","Union of Triumph personal reward","Vault of the Ancients"
];

export const CHEST_SOURCES = [
  "Arena","Bank","Clan wealth","Citadel","Elven Citadel","Cursed Citadel","Level 10 Crypt","Level 10 Citadel","Level 15 Crypt","Level 15 Citadel","Level 15 epic Crypt","Level 15 rare Crypt","Level 16 heroic Monster","Level 17 heroic Monster","Level 18 heroic Monster","Level 19 heroic Monster","Level 20 heroic Monster","Level 21 heroic Monster","Level 22 heroic Monster","Level 23 heroic Monster","Level 24 heroic Monster","Level 25 heroic Monster","Level 26 heroic Monster","Level 27 heroic Monster","Level 28 heroic Monster","Level 29 heroic Monster","Level 30 heroic Monster","Level 31 heroic Monster","Level 32 heroic Monster","Level 33 heroic Monster","Level 34 heroic Monster","Level 35 heroic Monster","Level 36 heroic Monster","Level 37 heroic Monster","Level 38 heroic Monster","Level 39 heroic Monster","Level 40 heroic Monster","Level 41 heroic Monster","Level 42 heroic Monster","Level 43 heroic Monster","Level 44 heroic Monster","Level 20 Crypt","Level 20 Citadel","Level 20 epic Crypt","Level 20 rare Crypt","Level 25 Crypt","Level 25 Citadel","Level 25 epic Crypt","Level 25 rare Crypt","Level 30 Crypt","Level 30 epic Crypt","Level 30 rare Crypt","Level 30-34 Vault of the Ancients","Level 35-39 Vault of the Ancients","Level 35 epic Crypt","Level 40-44 Vault of the Ancients","Level 45 Vault of the Ancients","Mercenary Exchange","Rise of the Ancients event","Union of Triumph personal reward","Vault of the Ancients","Lvl 20-24 Raid Runic squad","Lvl 25-29 Raid Runic squad","Lvl 30-34 Raid Runic squad","Lvl 35-39 Raid Runic squad","Lvl 40-44 Raid Runic squad","Lvl 45 Raid Runic squad"
];
