export const ROUTES = {
  HOME: 'home',
  INFO: 'info',
  NAVIGATION: 'navigation',
  ADMIN_PANEL: 'adminPanel',
  MANAGE_PLAYERS: 'managePlayers',
  MANAGE_RANKS: 'manageRanks',
  MANAGE_TROOP_STRENGTHS: 'manageTroopStrengths',
  MANAGE_NORMS: 'manageNorms',
  MANAGE_CHEST_MAPPING: 'manageChestMapping',
  ADMIN_REGISTRATION: 'adminRegistration',
  MANAGE_ADMIN_REQUESTS: 'manageAdminRequests',
  MANAGE_ADMINISTRATORS: 'manageAdministrators',
  UPLOAD_RESULTS: 'uploadResults',
  CREATE_PERIOD: 'createPeriod',
  CURRENT_TOTAL_EVENT: 'currentTotalEvent',
  STANDARDS_EVALUATION: 'standardsEvaluation',
  EVENT_ARCHIVE: 'eventArchive',
  TOP_TEN: 'topTen',
  HALL_OF_CHAMPIONS: 'hallOfChampions',
  CONTACT_FORM: 'contactForm',
  CURRENT_TOTAL_EVENT_ADMIN: 'currentTotalEventAdmin',
  EVENT_ARCHIVE_ADMIN: 'eventArchiveAdmin',
  EMAIL_TEST: 'emailTest',
};