export const ROUTES = {
  HOME: 'home',
  ARTIST_PROFILE: 'artistProfile',
  PROJECTS: 'projects',
  PROJECT_WE_STAND_TOGETHER: 'projectWeStandTogether',
  PROJECT_KING_CHRIS: 'projectKingChris',
  UFF_MUSIK: 'uffMusik',
  MUSIK_SHOP: 'musikShop',
  MUSIK_SHOP_KING_CHRIS: 'musikShopKingChris',
  MUSIK_SHOP_PO_FRIENDS_GOES_COUNTRY: 'musikShopPOFriendsGoesCountry',
  MUSIK_SHOP_LOVE_BEYOND_THE_SILENCE: 'musikShopLoveBeyondTheSilence',
  MUSIK_SHOP_WE_STAND_TOGETHER: 'musikShopWeStandTogether',
  MUSIK_SHOP_PRINCE_O_ELYRIA: 'musikShopPrinceOElyria',
  MUSIK_SHOP_THE_ASTRONAUT: 'musikShopTheAstronaut',
};